/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/universal_register.v:1.1-28.10" *)
module universal_register(clk, en, areset, sil, sir, sel, pi, po, sol, sor);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [23:0] _16_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _17_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [7:0] _18_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [7:0] _19_;
  (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _20_;
  (* src = "rtl/universal_register.v:2.23-2.29" *)
  input areset;
  wire areset;
  (* src = "rtl/universal_register.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "rtl/universal_register.v:2.20-2.22" *)
  input en;
  wire en;
  (* src = "rtl/universal_register.v:4.22-4.24" *)
  input [7:0] pi;
  wire [7:0] pi;
  (* src = "rtl/universal_register.v:5.22-5.24" *)
  output [7:0] po;
  reg [7:0] po;
  (* src = "rtl/universal_register.v:3.22-3.25" *)
  input [1:0] sel;
  wire [1:0] sel;
  (* src = "rtl/universal_register.v:2.30-2.33" *)
  input sil;
  wire sil;
  (* src = "rtl/universal_register.v:2.34-2.37" *)
  input sir;
  wire sir;
  (* src = "rtl/universal_register.v:6.17-6.20" *)
  output sol;
  wire sol;
  (* src = "rtl/universal_register.v:6.21-6.24" *)
  output sor;
  wire sor;
  (* src = "rtl/universal_register.v:9.1-24.4" *)
  always @(posedge clk, posedge areset)
    if (areset) po[0] <= 1'h0;
    else if (_01_) po[0] <= _18_[0];
  (* src = "rtl/universal_register.v:9.1-24.4" *)
  always @(posedge clk, posedge areset)
    if (areset) po[1] <= 1'h0;
    else if (_01_) po[1] <= _18_[1];
  (* src = "rtl/universal_register.v:9.1-24.4" *)
  always @(posedge clk, posedge areset)
    if (areset) po[2] <= 1'h0;
    else if (_01_) po[2] <= _18_[2];
  (* src = "rtl/universal_register.v:9.1-24.4" *)
  always @(posedge clk, posedge areset)
    if (areset) po[3] <= 1'h0;
    else if (_01_) po[3] <= _18_[3];
  (* src = "rtl/universal_register.v:9.1-24.4" *)
  always @(posedge clk, posedge areset)
    if (areset) po[4] <= 1'h0;
    else if (_01_) po[4] <= _18_[4];
  (* src = "rtl/universal_register.v:9.1-24.4" *)
  always @(posedge clk, posedge areset)
    if (areset) po[5] <= 1'h0;
    else if (_01_) po[5] <= _18_[5];
  (* src = "rtl/universal_register.v:9.1-24.4" *)
  always @(posedge clk, posedge areset)
    if (areset) po[6] <= 1'h0;
    else if (_01_) po[6] <= _18_[6];
  (* src = "rtl/universal_register.v:9.1-24.4" *)
  always @(posedge clk, posedge areset)
    if (areset) po[7] <= 1'h0;
    else if (_01_) po[7] <= _18_[7];
  assign _03_ = ~sel[1];
  assign _02_ = ~sel[0];
  assign _13_ = _02_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16" *)  _03_;
  assign _14_ = sel[0] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16" *)  _03_;
  assign _15_ = _02_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16" *)  sel[1];
  assign _01_ = en & _00_;
  assign _04_ = _16_[7] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[15];
  assign _19_[7] = _04_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[23];
  assign _05_ = _16_[6] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[14];
  assign _19_[6] = _05_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[22];
  assign _06_ = _16_[5] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[13];
  assign _19_[5] = _06_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[21];
  assign _07_ = _16_[4] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[12];
  assign _19_[4] = _07_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[20];
  assign _08_ = _16_[3] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[11];
  assign _19_[3] = _08_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[19];
  assign _09_ = _16_[2] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[10];
  assign _19_[2] = _09_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[18];
  assign _10_ = _16_[1] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[9];
  assign _19_[1] = _10_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[17];
  assign _11_ = _16_[0] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[8];
  assign _19_[0] = _11_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:593.20-593.31" *)  _16_[16];
  assign _12_ = _17_[0] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _17_[1];
  assign _20_ = _12_ |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.15" *)  _17_[2];
  assign _00_ = sel[0] |(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16" *)  sel[1];
  assign _17_[0] = ~(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16" *) _13_;
  assign _17_[1] = ~(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16" *) _14_;
  assign _17_[2] = ~(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16" *) _15_;
  assign _18_[0] = _20_ ? (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _19_[0] : 1'hx;
  assign _18_[1] = _20_ ? (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _19_[1] : 1'hx;
  assign _18_[2] = _20_ ? (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _19_[2] : 1'hx;
  assign _18_[3] = _20_ ? (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _19_[3] : 1'hx;
  assign _18_[4] = _20_ ? (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _19_[4] : 1'hx;
  assign _18_[5] = _20_ ? (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _19_[5] : 1'hx;
  assign _18_[6] = _20_ ? (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _19_[6] : 1'hx;
  assign _18_[7] = _20_ ? (* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:597.13-597.25" *) _19_[7] : 1'hx;
  assign _16_[16] = sil &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[2];
  assign _16_[17] = po[0] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[2];
  assign _16_[18] = po[1] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[2];
  assign _16_[19] = po[2] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[2];
  assign _16_[20] = po[3] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[2];
  assign _16_[21] = po[4] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[2];
  assign _16_[22] = po[5] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[2];
  assign _16_[23] = po[6] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[2];
  assign _16_[8] = po[1] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[1];
  assign _16_[9] = po[2] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[1];
  assign _16_[10] = po[3] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[1];
  assign _16_[11] = po[4] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[1];
  assign _16_[12] = po[5] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[1];
  assign _16_[13] = po[6] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[1];
  assign _16_[14] = po[7] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[1];
  assign _16_[15] = sir &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[1];
  assign _16_[0] = pi[0] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[0];
  assign _16_[1] = pi[1] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[0];
  assign _16_[2] = pi[2] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[0];
  assign _16_[3] = pi[3] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[0];
  assign _16_[4] = pi[4] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[0];
  assign _16_[5] = pi[5] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[0];
  assign _16_[6] = pi[6] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[0];
  assign _16_[7] = pi[7] &(* src = "rtl/universal_register.v:0.0-0.0|rtl/universal_register.v:14.9-20.16|/usr/bin/../share/yosys/techmap.v:585.44-585.84" *)  _17_[0];
  assign sol = po[7];
  assign sor = po[0];
endmodule
